PyMPack/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('apps.persona.urls')),
]

apps/persona/urls.py
from django.urls import path
from apps.persona import views

app_name='persona'

urlpatterns = [
    path('',views.PersonaList.as_view(),name="list_persona"),
    path('crear',views.PersonaCreate.as_view(),name="create_persona"),
    path('editar/<pk>',views.PersonaUpdate.as_view(),name="update_persona"),
    path('eliminar/<pk>', views.PersonaDelete.as_view(), name="delete_persona"),
    #path('data',views.recibir_data,name="recibir_data"),
]

apps/persona/models.py
from django.db import models

# Create your models here.
class Categoria(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    image = models.URLField()
    description = models.TextField()

    def __str__(self):
        return '{}'.format(self.name)

class Persona(models.Model):
    nombre = models.CharField(max_length=70)
    apellido = models.CharField(max_length=50)
    dni = models.CharField(max_length=8)
    sexo = models.CharField(max_length=20)
    fecha_nac = models.DateField()
    correo_electronico = models.CharField(max_length=50)
    categoria = models.ForeignKey(Categoria, null=True, blank=True, on_delete=models.CASCADE)

apps/persona/forms.py
from django import forms

from apps.persona.models import Persona


class PersonaForm(forms.ModelForm):
    class Meta:
        model=Persona
        fields = [
            'nombre',
            'apellido',
            'dni',
            'sexo',
            'fecha_nac',
            'correo_electronico',
            'categoria',
        ]

        labels = {
            'nombre': 'Nombre',
            'apellido': 'Apellido',
            'dni':'DNI',
            'sexo':'Sexo',
            'fecha_nac':'Fecha de Nacimiento',
            'correo_electronico':'Correo Electronico',
            'categoria':'Categoria',
        }

        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'apellido':forms.TextInput(attrs={'class': 'form-control'}),
            'dni': forms.NumberInput(attrs={
                                            'class': 'form-control',
                                            'id': 'number_field',
                                            'oninput': 'limit_input(8)'
                                    }),
            'sexo': forms.Select(choices=(
                                            ('Hombre','Hombre'),
                                            ('Mujer','Mujer'),
                                          ),
                                attrs={
                                    'class': 'form-control',
                                } ),
            'fecha_nac': forms.DateInput(attrs={
                                    'class': 'form-control',
                                    'placeholder':'Ejemplo: XX/XX/XXXX',
                                } ),
            'correo_electronico': forms.EmailInput(attrs={
                                    'class': 'form-control',
                                } ),
            'categoria': forms.Select(attrs={'class':'form-control'}),
        }

    def clean_dni(self):
        dni = self.cleaned_data['dni']
        if not len(dni)==8:
            raise forms.ValidationError('El dni debe contener 8 digitos')
        return dni

apps/persona/views.py
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import CreateView,ListView,UpdateView,DeleteView
# Create your views here.
from algoritmos.extras import leer_json
from apps.persona.forms import PersonaForm
from apps.persona.models import Persona, Categoria


class PersonaList(ListView):
    model = Persona
    template_name = "persona/persona_list.html"
    paginate_by = 5

class PersonaCreate(CreateView):
    model = Persona
    form_class = PersonaForm
    template_name = "persona/persona_form.html"
    success_url= reverse_lazy('persona:list_persona')

class PersonaUpdate(UpdateView):
    model = Persona
    form_class = PersonaForm
    template_name = 'persona/persona_form.html'
    success_url = reverse_lazy('persona:list_persona')

class PersonaDelete(DeleteView):
    model = Persona
    template_name = 'persona/persona_delete.html'
    success_url = reverse_lazy('persona:list_persona')





#VIEW PARA LLENAR DATOS CON EL URL DADO POR PyMPack
def recibir_data(request):
    data=leer_json('http://ec2-34-236-250-113.compute-1.amazonaws.com:9000/categories/')
    for dato in data:
        obj, created = Categoria.objects.get_or_create(
            id=dato['id'],
            defaults={
                        'name':dato['name'],
                        'image':dato['image'],
                        'description':dato['description']
                    }
        )
    return HttpResponse(data)

templates/base/base.html
{% load staticfiles %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block extrastatic %}
    {%  endblock %}
    <link rel="icon" href="{% static 'icon/icono.png' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{% block titulo %}Documento{% endblock %}</title>
</head>
<body>
    <div class="container">
        {% block navegador %}
        <div class="bs-docs-section clearfix">
            <div class="row">
                <div class="col-lg-12">
                    <div class="bs-component">
                      <nav class="navbar navbar-default">
                        <div class="container-fluid">
                            <div class="navbar-header">
                                <a class="navbar-brand" href="{% url 'persona:list_persona' %}">Bienvenido</a>
                            </div>
                                 <ul class="nav navbar-nav">
                                     <li><a href="{% url 'persona:list_persona' %}">Listar Persona</a></li>
                                     <li><a href="{% url 'persona:create_persona' %}">Crear Persona</a></li>
                                 </ul>
                                <ul class="nav navbar-nav navbar-right">
                                  <li class="dropdown"><a href="https://github.com/stevematos/Demo" onclick="pageTracker._link(this.href); return false;">Ver Codigo</a>
                                </ul>
                        </div>
                      </nav>
                    </div>
                </div>
            </div>
        </div>
       {% endblock %}﻿

    </div>
    {% block header %}
    {% endblock %}
    <div class="container">
    {% block contenido %}
    {% endblock %}
    {% block footer %}
        <h5>Steve Sader Matos Manguinuri</h5>
        <h5>Correo: steve.matos@unmsm.edu.pe o s.s.m.m_98@hotmail.com</h5>
        <h5>Celular:936015877</h5>
    {% endblock %}
     </div>
</body>
</html>

templates/persona/persona_delete.html
{% extends 'base/base.html' %}
{% block titulo %}
    Eliminar Persona
{% endblock %}
{% block contenido %}
<form method="post">
	{% csrf_token %}
	<h3>¿Desea eliminar a la persona {{ object.nombre }}?</h3>
	<button class="btn btn-danger" type='submit'>Si,lo deseo eliminar</button>
	<a class="btn btn-default" href="{% url 'persona:list_persona' %}">No,Cancelar</a>
</form>
{% endblock %}

templates/persona/persona_form.html
{% extends 'base/base.html' %}
{% block titulo %}
    Formulario Persona
{% endblock %}
{% block extrastatic %}
    <script type="text/javascript">
        function limit_input(n) {
            var field = document.getElementById("number_field");
            var max_length = n;
            if (field.value.length > max_length) {
                field.value = field.value.slice(0, max_length);
            }
        }
    </script>
{% endblock %}

{% block contenido %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type='submit' class='btn btn-primary' value="Save">Guardar</button>
</form>
{% endblock %}

templates/persona/persona_list.html
{%  extends 'base/base.html' %}

{% block titulo %}
    Lista de personas
{% endblock %}


{% block contenido %}
    <table class="table table-bordered">
        <thead>
            <tr>
                <td>#</td>
                <td>Nombre</td>
                <td>Apellido</td>
                <td>Dni</td>
                <td>Sexo</td>
                <td>Fecha Nacimiento</td>
                <td>Correo Electronico</td>
                <td>Categoria</td>
                <td>Acciones</td>
            </tr>
        </thead>
        <tbody>
            {% if object_list %}
            {% for persona in object_list %}
            <tr>
                <td>{{persona.id}}</td>
                <td>{{persona.nombre}}</td>
                <td>{{persona.apellido}}</td>
                <td>{{persona.dni}}</td>
                <td>{{persona.sexo}}</td>
                <td>{{persona.fecha_nac}}</td>
                <td>{{persona.correo_electronico}}</td>
                <td><div><img src="{{persona.categoria.image}}"></div>
                    <div>{{ persona.categoria.name }}</div></td>
                <td>
                    <a class="btn btn-primary" href="{% url 'persona:update_persona' persona.id%}">Editar</a>
                    <a class="btn btn-danger" href="{% url 'persona:delete_persona' persona.id %}">Eliminar</a>
                </td>
            </tr>
            {% endfor %}

            {% else %}
            <h1>No hay registros de mascotas</h1>
            {% endif %}
        </tbody>
    </table>
    <ul class="pager">
        <li>
            {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
            {% endif %}
            </li>
        <li>
            {% if page_obj.has_next %}
             <a href="?page={{ page_obj.next_page_number }}">Next</a>
            {% endif %}
        </li>
    </ul>
{% endblock %}